export const quickServices = [
  {
    id: "pan-card",
    icon: "🪪",
    label: "PAN Card Help",
    labelHi: "पैन कार्ड सहायता",
    sub: "New / Correction",
    subHi: "नया / सुधार",
    category: "certificates",
    color: "bg-orange-50 text-orange-600 border-orange-100",
    desc: "New PAN card, correction, update aur document support ke liye help.",
    descHi: "नया पैन कार्ड, सुधार, अपडेट और दस्तावेज सहायता।",
    docs: [
      "Aadhaar Card",
      "Mobile Number",
      "Passport Size Photo",
      "Signature",
    ],
  },
  {
    id: "income-certificate",
    icon: "📄",
    label: "Income Certificate",
    labelHi: "आय प्रमाण पत्र",
    sub: "Income proof help",
    subHi: "आय प्रमाण पत्र",
    category: "certificates",
    color: "bg-blue-50 text-blue-600 border-blue-100",
    desc: "Scholarship, admission, pension aur online applications ke liye income certificate support.",
    descHi: "छात्रवृत्ति, प्रवेश, पेंशन और ऑनलाइन आवेदन के लिए आय प्रमाण पत्र सहायता।",
    docs: [
      "Aadhaar Card",
      "Passport Size Photo",
      "Mobile Number",
      "Family Details",
      "Income Related Supporting Document",
      "Self Declaration Form if required",
    ],
  },
  {
    id: "caste-certificate",
    icon: "📑",
    label: "Caste Certificate",
    labelHi: "जाति प्रमाण पत्र",
    sub: "OBC / SC / ST help",
    subHi: "जाति प्रमाण पत्र",
    category: "certificates",
    color: "bg-emerald-50 text-emerald-600 border-emerald-100",
    desc: "Scholarship, reservation, admission aur government forms ke liye caste certificate support.",
    descHi: "छात्रवृत्ति, आरक्षण, प्रवेश और सरकारी फॉर्म के लिए जाति प्रमाण पत्र सहायता।",
    docs: [
      "Aadhaar Card",
      "Passport Size Photo",
      "Mobile Number",
      "Family Details",
      "Old Caste Certificate if available",
      "Self Declaration Form if required",
    ],
  },
  {
    id: "residence-certificate",
    icon: "🏠",
    label: "Residence Certificate",
    labelHi: "निवास प्रमाण पत्र",
    sub: "Address proof help",
    subHi: "निवास प्रमाण पत्र",
    category: "certificates",
    color: "bg-sky-50 text-sky-600 border-sky-100",
    desc: "Address proof, admission, local recruitment aur other services ke liye residence certificate support.",
    descHi: "पता प्रमाण, प्रवेश, स्थानीय भर्ती और अन्य सेवाओं के लिए निवास प्रमाण पत्र सहायता।",
    docs: [
      "Aadhaar Card",
      "Passport Size Photo",
      "Mobile Number",
      "Address Proof",
      "Ration Card if available",
      "Self Declaration Form if required",
    ],
  },
  {
    id: "scholarship",
    icon: "🎓",
    label: "Scholarship Form",
    labelHi: "छात्रवृत्ति फॉर्म",
    sub: "UP / NSP Help",
    subHi: "यूपी / एनएसपी सहायता",
    category: "scholarship",
    color: "bg-purple-50 text-purple-600 border-purple-100",
    desc: "UP Scholarship, NSP, renewal, correction aur status check ke liye help.",
    descHi: "यूपी छात्रवृत्ति, एनएसपी, नवीनीकरण, सुधार और स्थिति जांच सहायता।",
    docs: [
      "Aadhaar Card",
      "Bank Passbook",
      "Marksheet",
      "Income Certificate",
      "Caste Certificate if required",
      "School / College Details",
      "Mobile Number",
      "Fee Receipt if required",
    ],
  },
  {
    id: "job-form",
    icon: "💼",
    label: "Job Form",
    labelHi: "नौकरी फॉर्म",
    sub: "Govt Exam Forms",
    subHi: "सरकारी परीक्षा फॉर्म",
    category: "jobs_exams",
    color: "bg-rose-50 text-rose-600 border-rose-100",
    desc: "Government job forms, exam forms aur online application support.",
    descHi: "सरकारी नौकरी फॉर्म, परीक्षा फॉर्म और ऑनलाइन आवेदन सहायता।",
    docs: [
      "Aadhaar Card",
      "Passport Size Photo",
      "Signature",
      "Qualification Details",
      "Category Certificate if required",
      "Mobile Number",
    ],
  },
  {
    id: "admit-card",
    icon: "🖨️",
    label: "Admit Card / Result",
    labelHi: "प्रवेश पत्र / परिणाम",
    sub: "Download & Print",
    subHi: "डाउनलोड और प्रिंट",
    category: "jobs_exams",
    color: "bg-amber-50 text-amber-600 border-amber-100",
    desc: "Admit card download, result print aur scorecard print support.",
    descHi: "प्रवेश पत्र डाउनलोड, परिणाम प्रिंट और स्कोरकार्ड प्रिंट सहायता।",
    docs: [
      "Registration Number",
      "Date of Birth",
      "Mobile Number",
      "Password if required",
      "Roll Number if required",
    ],
  },
  {
    id: "bill-payment",
    icon: "💳",
    label: "Bill Payment",
    labelHi: "बिल भुगतान",
    sub: "Electricity / Recharge",
    subHi: "बिजली / रिचार्ज",
    category: "payments",
    color: "bg-teal-50 text-teal-600 border-teal-100",
    desc: "Electricity bill, recharge aur other online payment support.",
    descHi: "बिजली बिल, रिचार्ज और अन्य ऑनलाइन भुगतान सहायता।",
    docs: [
      "Consumer Number",
      "Mobile Number",
      "Bill Copy if available",
    ],
  },
  {
    id: "photocopy-print",
    icon: "📠",
    label: "Print / Scan",
    labelHi: "प्रिंट / स्कैन",
    sub: "Xerox & Document",
    subHi: "फोटोकॉपी और दस्तावेज",
    category: "documents",
    color: "bg-slate-100 text-slate-700 border-slate-200",
    desc: "Photocopy, scan, print, PDF aur document related help.",
    descHi: "फोटोकॉपी, स्कैन, प्रिंट, PDF और दस्तावेज सहायता।",
    docs: [
      "Original Document",
      "PDF / Photo File",
      "Mobile or Pen Drive if available",
    ],
  },
  {
    id: "aadhaar-pan-link",
    icon: "🔗",
    label: "Aadhaar PAN Link",
    labelHi: "आधार पैन लिंक",
    sub: "Linking Help",
    subHi: "लिंकिंग सहायता",
    category: "documents",
    color: "bg-lime-50 text-lime-700 border-lime-100",
    desc: "Aadhaar PAN linking aur related online support.",
    descHi: "आधार पैन लिंकिंग और संबंधित ऑनलाइन सहायता।",
    docs: [
      "Aadhaar Card",
      "PAN Card",
      "Mobile Number",
    ],
  },
];

export const certificateServices = quickServices
  .filter((service) =>
    ["income-certificate", "caste-certificate", "residence-certificate"].includes(
      service.id
    )
  )
  .map((service) => ({
    id: service.id,
    title: service.label,
    titleHi: service.labelHi,
    desc: service.desc,
    descHi: service.descHi,
    fee: "Fee as per service",
    icon: service.icon,
    category: service.category,
    docs: service.docs,
  }));